apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-backstage
  labels:
    app: snake-backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake-backstage
  template:
    metadata:
      labels:
        app: snake-backstage
    spec:
      containers:
        - name: snake-backstage
          # image: asia.gcr.io/cqi-operation/snakebackstage:220506.net6.t1
          image: gcr.io/stellar-38931/sk-backstage:test.0512.1
          imagePullPolicy: Always 
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            
            - name: ExternalServers__UserServer
              valueFrom:
                configMapKeyRef:
                  name: configmap-snakebackstage
                  key: UserServer
            - name: ExternalServers__TableServer
              valueFrom:
                configMapKeyRef:
                  name: configmap-snakebackstage
                  key: TableServer
            # - name: ConnectionStrings__DefaultConnection
            #  valueFrom:
            #    configMapKeyRef:
            #      name: configmap-snakebackstage
            #      key: MySQL-Connection
            - name: ExternalServers__GoogleSheet
              valueFrom:
                configMapKeyRef:
                  name: configmap-snakebackstage
                  key: GoogleSheet

            - name: MySQL__DoMigrationOnlyThenExit
              value: "false"
            - name: MySQL__IP
              valueFrom:
                configMapKeyRef:
                  name: configmap-snakebackstage
                  key: MySQL-IP
            - name: MySQL__Port
              valueFrom:
                configMapKeyRef:
                  name: configmap-snakebackstage
                  key: MySQL-Port
            - name: MySQL__DatabaseName
              valueFrom:
                configMapKeyRef:
                  name: configmap-snakebackstage
                  key: MySQL-DatabaseName
            - name: MySQL__User
              value: 'root'
            - name: MySQL__Password
              valueFrom:
                configMapKeyRef:
                  name: configmap-snakebackstage
                  key: MySQL-Password
            - name: PathBase
              value: "/"
          volumeMounts:
            - mountPath: /etc/localtime
              name: tz-config  
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        


            
            
      