apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-snakebackstage
data:
  UserServer: "http://service-user:5500"
  TableServer: "http://service-table:5000"
  MySQL-Connection: "Server=snake-backstage-db;Port=3306;database=SnakeBackstage;user id=root;password=cqig7777"

  # alpha
  GoogleSheet: "https://docs.google.com/spreadsheets/d/1CB9PFeohG3HGYI06_J_KQj82FXOFbOajnr_1X8tCFTw/edit?usp=sharing"
  # Beta
  # GoogleSheet: "https://docs.google.com/spreadsheets/d/1ne-UMOQBN_i9wAMgY4H3GtsC31bWb2ovS-y66-XNDB4/edit?usp=sharing"

  # live
  # GoogleSheet: "https://docs.google.com/spreadsheets/d/1-Pla2rvRNoV_FIOYeOho_vTG9URI-td_KDAoLI2bwfw/edit?usp=sharing"