apiVersion: v1
kind: ConfigMap
metadata:
  name: asianleague-web
data:
  UserServer: "http://service-user:5500"
  TableServer: "http://service-table:5000"
  MySQL-Connection: "Server=snake-backstage-db;Port=3306;database=SnakeBackstage;user id=root;password=cqig7777"

  # NFT
  GoogleApis: "https://storage.googleapis.com/pps-nft/{0}/{1}.png"
  OpenSeaURL: "https://testnets.opensea.io/collection/character-w7pmtkc0wg"
  OpenSeaLink: "https://testnets.opensea.io/assets/{0}/{1}"
  XApiKey: "7dc2ebcab71e414db6a5c97d91d902ad"
  AssetContractAddress: "0x2DE6D9904AC58D6e50c328a0177c038b57F9E2D3"
  RetrieveAssets: "https://testnets-api.opensea.io/api/v1/assets?asset_contract_address={0}&order_direction=asc&offset={1}&limit={2}"
  RetrieveOffers: "https://api.opensea.io/api/v1/asset/{0}/{1}/offers?limit=20"
